#!/usr/bin/env bash
# Regenerate .env.local from the running local Supabase stack, so the app points
# at Docker Postgres instead of the hosted project. Run after `npm run db:start`.
set -euo pipefail

cd "$(dirname "$0")/.."

status=$(npx supabase status -o env \
  --override-name api.url=SUPABASE_URL \
  --override-name auth.anon_key=SUPABASE_KEY \
  --override-name auth.service_role_key=NUXT_SUPABASE_SECRET_KEY 2>/dev/null || true)

if ! grep -q '^SUPABASE_URL=' <<< "$status"; then
  echo "Local Supabase isn't running, or Docker isn't reachable from this shell." >&2
  echo >&2
  echo "  1. Start Docker Desktop." >&2
  echo "  2. Settings -> Resources -> WSL integration -> enable this distro." >&2
  echo "  3. npm run db:start" >&2
  exit 1
fi

# Keep any Stripe test keys already in .env.local rather than blanking them.
keep() {
  if [ -f .env.local ]; then
    grep -m1 "^$1=" .env.local | cut -d= -f2- || true
  fi
}

stripe_secret=$(keep NUXT_STRIPE_SECRET_KEY)
stripe_webhook=$(keep NUXT_STRIPE_WEBHOOK_SECRET)
stripe_public=$(keep NUXT_PUBLIC_STRIPE_PUBLISHABLE_KEY)

{
  echo "# Generated by scripts/local-env.sh — re-run \`npm run db:env\` to refresh."
  echo "# Points the app at the local Supabase stack (npm run db:start)."
  echo
  grep -E '^(SUPABASE_URL|SUPABASE_KEY|NUXT_SUPABASE_SECRET_KEY)=' <<< "$status"
  echo
  echo 'NUXT_PUBLIC_SITE_URL="http://localhost:3000"'
  echo
  echo '# Stripe test mode — dues stay disabled while these are blank.'
  echo "NUXT_STRIPE_SECRET_KEY=${stripe_secret:-\"\"}"
  echo "NUXT_STRIPE_WEBHOOK_SECRET=${stripe_webhook:-\"\"}"
  echo "NUXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${stripe_public:-\"\"}"
} > .env.local

field() {
  grep -m1 "^$1=" <<< "$status" | cut -d= -f2- | tr -d '"'
}

echo "Wrote .env.local"
echo "  Studio:      $(field STUDIO_URL)"
echo "  Test inbox:  $(field MAILPIT_URL)  (sign-in links land here)"
echo "  Start the app with: npm run dev:local"
